package model;
// Generated Mar 15, 2017 12:52:28 AM by Hibernate Tools 4.3.1

/**
 * Users generated by hbm2java
 */
public class HRM  implements java.io.Serializable {


     private Integer hrm_id;
     private String hrm_username;
     private String hrm_password;
     private String hrm_name;

    public HRM() {
    }

    public HRM(String uname, String pass, String email) {
       this.hrm_username = uname;
       this.hrm_password = pass;
       this.hrm_name = email;
    }
   
    public Integer getHrm_id() {
        return this.hrm_id;
    }
    
    public void setHrm_id(Integer hrm_id) {
        this.hrm_id = hrm_id;
    }
    public String getHrm_username() {
        return this.hrm_username;
    }
    
    public void setHrm_username(String hrm_username) {
        this.hrm_username = hrm_username;
    }
    public String getHrm_password() {
        return this.hrm_password;
    }
    
    public void setHrm_password(String hrm_password) {
        this.hrm_password = hrm_password;
    }
    public String getHrm_name() {
        return this.hrm_name;
    }
    
    public void setHrm_name(String hrm_name) {
        this.hrm_name = hrm_name;
    }




}


